# -*- coding: utf-8 -*-
"""ДЗ №1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kM6YF2lycNCwLhj3WRxg4-IxTFOp-jad
"""

#1

"""Будем осуществлять работу с непростым набором данных о состоянии здоровья лошадей, испытывающих кишечные колики. 
Цель – максимально корректно заполнить пропуски.

Задание 1. Загрузка данных
Изучить представленный набор данных на основе описания его столбцов, 
загрузить его и оставить 8 столбцов для дальнейшего изучения: 
surgery?, Age, rectal temperature, pulse, respiratory rate, temperature of extremities, pain, outcome.
"""
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/obulygin/pyda_homeworks/master/statistics_basics/horse_data.csv',
  names = ['surgery?','Age','Hospital Number','rectal temperature',
         'pulse', 'respiratory rate', 'temperature of extremities',
         'peripheral pulse', 'mucous membranes', 'capillary refill time', 'pain',
         'peristalsis', 'abdominal distension', 'nasogastric tube', 'nasogastric reflux',
         'nasogastric reflux PH', 'rectal examination - feces', 'abdomen', 'packed cell volume',
         'total protein', 'abdominocentesis appearance', 'abdomcentesis total protein', 'outcome',
         'surgical lesion?', 'type of lesion 1', 'type of lesion 2', 'type of lesion 3', 'cp_data'
         ],
  header = None)

import numpy as np
new_df = df[['surgery?', 'Age', 'rectal temperature', 'pulse', 'respiratory rate', 'temperature of extremities', 'pain', 'outcome']]
new_df.head(15)
#df.info()

new_df = new_df.replace('?', np.nan)
new_df['Age'].unique()
new_df[['surgery?', 'pulse', 'rectal temperature', 'respiratory rate', 'temperature of extremities', 'pain', 'outcome']] = new_df[['surgery?', 'pulse', 'rectal temperature', 'respiratory rate', 'temperature of extremities', 'pain', 'outcome']].astype('float64')

new_df.info()

#2
"""Задание 2. Первичное изучение данных
Проанализировать значения по столбцам, рассчитать базовые статистики, найти выбросы.
"""
#new_df.query('Age > 1')
print('ПРОЦЕНТ ПРОПУСКОВ\n', (new_df.isna().mean() * 100).round(2))


print('\nОсновные параметры\n'.upper(),new_df.describe())

#df_withnan[df_withnan[['respiratory rate', 'pulse']].isna().any(1)]

print('\nМедиана\n'.upper(),new_df.median(),'\n')

print('Мода\n'.upper(), new_df.mode(), '\n')

q1 = new_df.quantile(0.25)
print('Первый квартиль\n'.upper(), q1, '\n')

q3 = new_df.quantile(0.75)
print('Третий квартиль\n'.upper(), q3,'\n')

iqr = q3 - q1

print('Межквартильный интервал\n'.upper(),iqr, '\n')



#для примера выбросы по столбцу "пульс"
q1_1 = new_df['pulse'].quantile(0.25)
print('Первый квартиль\n'.upper(), q1, '\n')
q3_1 = new_df['pulse'].quantile(0.75)
print('Третий квартиль\n'.upper(), q3,'\n')
iqr2 = q3_1- q1_1
lower_bound = q1_1 - (1.5 * iqr2) 
upper_bound = q3_1 + (1.5 * iqr2)
remove_outliers = new_df[~new_df['pulse'].between(lower_bound, upper_bound, inclusive=True)]
remove_outliers.info()
#new_df['pulse'].describe()
#пульс лошади может достигать 220-240 ударов, потому вряд ли что-то можно считать выбросом

#3
"""
Задание 3. Работа с пропусками
Рассчитать количество пропусков для всех выбранных столбцов. 
Принять и обосновать решение о методе заполнения пропусков по каждому столбцу на основе рассчитанных статистик и возможной взаимосвязи значений в них. 
Сформировать датафрейм, в котором пропуски будут отсутствовать.
"""



#new_df.describe()
new_df1 = new_df[new_df[['outcome']].isna().any(1)].fillna(1)
print(new_df1)


alive = new_df[new_df['outcome'] == 1]

death = new_df[new_df['outcome'] == 2]

euthan = new_df[new_df['outcome'] == 3]

death_all = pd.concat([death, euthan], axis = 0)


surg_outcome_nan = new_df1.index.tolist()

print('статистика по выжившим\n', alive.describe()) #статистика по выжившим
print('статистика по умершим\n',death.describe()) #статистика по умершим
print('статистика по усыплённым\n',euthan.describe()) #статистика по усыплённым
print('статистика по умершим и усыплённым', death_all.describe()) #статистика по умершим и усыплённым

print(new_df.loc[132]) 

"""В целом, чем больнее, тем больше вероятность, что потребуется хирургическое вмешательство"""
"""прохладные конечности указывают на возможный шок"""
"""температура в пределах допустимого(возможно опускается ввиду развития шока), пульс слегка повышен, что так же говорит о возможном шоке. """

#df.loc[132]
#surgical lesion - 1; type of lesion - 3111; abdomen - 5
#Поражение было хирургическим, основываясь на данных по вышеперечисленным параметрам.
#Следовательно предполагаем с большой вероятностью, что лошади проводилась операция. surgery? = 1

#Основываясь на значениях пульса и частоты дыхания можно предположить, что исход для лошади был положителен.
#Хотя боль и температура конечностей могут говорить об обратном, стоит понимать, что они являются субъективными показателями.
#Остальные показатели по большей части находятся в нормальных границах, что даёт возможность предположить о положительном исходе операции

#4

#Замена модой

#Выбор строк, где нет данных о пульсе, но известно, что боль находится в пределах от 0 до 2.
new_df2 = new_df[new_df[['pulse']].isna().any(1)]
new_df2 = new_df2.loc[new_df2['pain'] < 3]

#Замена модой из списка выживших
new_df2['pulse'] = new_df2['pulse'].fillna(alive['pulse'].mode()[0])
new_df2['rectal temperature'] = new_df2['rectal temperature'].fillna(alive['rectal temperature'].mode()[0])
new_df2['respiratory rate'] = new_df2['respiratory rate'].fillna(alive['respiratory rate'].mode()[0])

#Перевод индексов в список
pulse_nan_pain_max2 = new_df2.index.tolist()

################################################################################################################################################################################

#Выбор строк, где нет данных о пульсе и боли
new_df3 = new_df[new_df[['pulse']].isna().any(1)]
new_df3 = new_df3[new_df3[['pain']].isna().any(1)]

########################################################################################

#Выбор строк, где нет данных о пульсе и боли, исход положительный
new_df3_1 = new_df3.loc[new_df3['outcome'] == 1]

#Замена модой из списка выживших
new_df3_1['pulse'] = new_df3_1['pulse'].fillna(alive['pulse'].mode()[0])
new_df3_1['rectal temperature'] = new_df3_1['rectal temperature'].fillna(alive['rectal temperature'].mode()[0])
new_df3_1['respiratory rate'] = new_df3_1['respiratory rate'].fillna(alive['respiratory rate'].mode()[0])
new_df3_1['temperature of extremities'] = new_df3_1['temperature of extremities'].fillna(alive['temperature of extremities'].mode()[0])
new_df3_1['pain'] = new_df3_1['pain'].fillna(alive['pain'].mode()[0])

########################################################################################

#Выбор строк, где нет данных о пульсе и боли, исход отрицательный
new_df3_2 = new_df3.loc[new_df3['outcome'] == 2]

#Замена модой из списка умерших и усыплённых
new_df3_2['pulse'] = new_df3_2['pulse'].fillna(death_all['pulse'].mode()[0])
new_df3_2['rectal temperature'] = new_df3_2['rectal temperature'].fillna(death_all['rectal temperature'].mode()[0])
new_df3_2['respiratory rate'] = new_df3_2['respiratory rate'].fillna(death_all['respiratory rate'].mode()[0])
new_df3_2['temperature of extremities'] = new_df3_2['temperature of extremities'].fillna(death_all['temperature of extremities'].mode()[0])
new_df3_2['pain'] = new_df3_2['pain'].fillna(death_all['pain'].mode()[0])

########################################################################################

#Объединение в один список
df3 = pd.concat([new_df3_1, new_df3_2], axis = 0)
pulse_nan_pain_nan = df3.index.tolist()

################################################################################################################################################################################

#Замена медианой

#Выбор строк, где нет данных о пульсе, но известно, что боль находится в пределах от 3 до 5
new_df4 = new_df[new_df[['pulse']].isna().any(1)]
new_df4 = new_df4.loc[new_df4['pain'] >= 3]

########################################################################################

#Выбор строк, где нет данных о пульсе, но известно, что боль находится в пределах от 3 до 5 и исход положительный
new_df4_1 = new_df4.loc[new_df4['outcome'] == 1]

#Замена медианой из списка выживших
new_df4_1['pulse'] = new_df4_1['pulse'].fillna(alive['pulse'].median())
new_df4_1['temperature of extremities'] = new_df4_1['temperature of extremities'].fillna(alive['temperature of extremities'].median())
new_df4_1['respiratory rate'] = new_df4_1['respiratory rate'].fillna(alive['respiratory rate'].median())
new_df4_1['rectal temperature'] = new_df4_1['rectal temperature'].fillna(alive['rectal temperature'].median())

########################################################################################

#Выбор строк, где нет данных о пульсе, но известно, что боль находится в пределах от 3 до 5 и исход отрицательный
new_df4_2 = new_df4.loc[new_df4['outcome'] == 2]

#Замена медианой из списка умерших и усыплённых
new_df4_2['pulse'] = new_df4_2['pulse'].fillna(death_all['pulse'].median())
new_df4_2['respiratory rate'] = new_df4_2['respiratory rate'].fillna(death_all['respiratory rate'].median())
new_df4_2['rectal temperature'] = new_df4_2['rectal temperature'].fillna(death_all['rectal temperature'].median())

#Выбор строк, где нет данных о пульсе, но известно, что боль находится в пределах от 3 до 5 и исход отрицательный (усыпление)
new_df4_3 = new_df4.loc[new_df4['outcome'] == 3]

#Замена медианой из списка умерших и усыплённых
new_df4_3['pulse'] = new_df4_3['pulse'].fillna(death_all['pulse'].median())
new_df4_3['respiratory rate'] = new_df4_3['respiratory rate'].fillna(death_all['respiratory rate'].median())
new_df4_3['rectal temperature'] = new_df4_3['rectal temperature'].fillna(death_all['rectal temperature'].median())

########################################################################################

#Объединение в один список
df4 = pd.concat([new_df4_1, new_df4_2, new_df4_3], axis = 0)

pulse_nan_pain_min3 = df4.index.tolist()
general_list_pulse_nan = pulse_nan_pain_max2 + pulse_nan_pain_nan + pulse_nan_pain_min3 + surg_outcome_nan
len(set(general_list_pulse_nan))

#5

########################################################################################
# Копия фрейма
corrected_df = new_df.copy()

# Копию фрейма очищаем от строк с NaN
corrected_df = corrected_df.dropna()

# Объединяем в один фрейм заполненные строки
corrected_df = pd.concat([corrected_df, new_df1, new_df2, df3, df4], axis = 0)

# Создаем список из индексов с заполненными строками
corrected_list = corrected_df.index.tolist()

# Создаем копию фрейма , из которой будем вынимать строки с индексами
not_corrected_df = new_df.copy()
for i in corrected_list:
  not_corrected_df = not_corrected_df.drop(index = i)


# Объединяем фрейм с заполненными строками и очищенный по индексам 
corrected_df = pd.concat([corrected_df, not_corrected_df], axis = 0)


# Сортируем фрейм
corrected_df = corrected_df.sort_index()

corrected_df2 = corrected_df[corrected_df[['pain']].isna().any(1)]
print(corrected_df.describe())

print(new_df.describe())

#6

#Выбор строк, где нет данных о боли, исход положительный
corrected_df2_1 = corrected_df2.loc[corrected_df2['outcome'] == 1]

#можно предположить, что боль равняется моде из списка выживших, а остальные значения равны медиане
corrected_df2_1['pain'] = corrected_df2_1['pain'].fillna(alive['pain'].mode()[0])
corrected_df2_1['temperature of extremities'] = corrected_df2_1['temperature of extremities'].fillna(alive['temperature of extremities'].median()) 
corrected_df2_1['respiratory rate'] = corrected_df2_1['respiratory rate'].fillna(alive['respiratory rate'].median())
corrected_df2_1['rectal temperature'] = corrected_df2_1['rectal temperature'].fillna(alive['rectal temperature'].median())

###################################################################

#Выбор строк, где нет данных о боли, исход отрицательный
corrected_df2_2 = corrected_df2.loc#####################[corrected_df2['outcome'] == 2]

#можно предположить, что боль равняется моде из списка умерших и усыплённых, а остальные значения равны медиане
corrected_df2_2['pain'] = corrected_df2_2['pain'].fillna(death_all['pain'].mode()[0]) 
corrected_df2_2['temperature of extremities'] = corrected_df2_2['temperature of extremities'].fillna(death_all['temperature of extremities'].median()) 
corrected_df2_2['respiratory rate'] = corrected_df2_2['respiratory rate'].fillna(death_all['respiratory rate'].median())
corrected_df2_2['rectal temperature'] = corrected_df2_2['rectal temperature'].fillna(death_all['rectal temperature'].median())

########################################################################################

#Выбор строк, где нет данных о боли, исход отрицательный (усыпление)
corrected_df2_3 = corrected_df2.loc[corrected_df2['outcome'] == 3]

#можно предположить, что боль как и остальные значения равны медиане из списка умерших и усыплённых.
corrected_df2_3['pain'] = corrected_df2_3['pain'].fillna(death_all['pain'].median())
corrected_df2_3['temperature of extremities'] = corrected_df2_3['temperature of extremities'].fillna(death_all['temperature of extremities'].median()) 
corrected_df2_3['respiratory rate'] = corrected_df2_3['respiratory rate'].fillna(death_all['respiratory rate'].median())
corrected_df2_3['rectal temperature'] = corrected_df2_3['rectal temperature'].fillna(death_all['rectal temperature'].median())

########################################################################################

#Объединение в один список
cor_df3 = pd.concat([corrected_df2_1, corrected_df2_2, corrected_df2_3], axis = 0)
corrected_list2 = cor_df3.index.tolist()
not_corrected_df2 = corrected_df.copy()
for i in corrected_list2:
  not_corrected_df2 = not_corrected_df2.drop(index = i)

corrected_df2 = pd.concat([cor_df3, not_corrected_df2], axis = 0)
corrected_df2 = corrected_df2.sort_index()

#7

cor_df4 = corrected_df2[corrected_df2[['rectal temperature']].isna().any(1)]
cor_df4_1 = cor_df4[cor_df4['outcome'] == 1]

cor_df4_1['respiratory rate'] = cor_df4_1['respiratory rate'].fillna(alive['respiratory rate'].median())
cor_df4_1['rectal temperature'] = cor_df4_1['rectal temperature'].fillna(alive['rectal temperature'].median())
cor_df4_1

cor_df4_2 = pd.concat([cor_df4[cor_df4['outcome'] == 2], cor_df4[cor_df4['outcome'] == 3]], axis = 0)
cor_df4_2['respiratory rate'] = cor_df4_2['respiratory rate'].fillna(death_all['respiratory rate'].median())
cor_df4_2['rectal temperature'] = cor_df4_2['rectal temperature'].fillna(death_all['rectal temperature'].median())
cor_df4_2['temperature of extremities'] = cor_df4_2['temperature of extremities'].fillna(death_all['temperature of extremities'].median()) 
cor_df4_2

df5 = pd.concat([cor_df4_1, cor_df4_2],axis=0)
df5

corrected_list3 = df5.index.tolist()
not_corrected_df3 = corrected_df2.copy()
for i in corrected_list3:
  not_corrected_df3 = not_corrected_df3.drop(index = i)

corrected_df3 = pd.concat([df5, not_corrected_df3], axis = 0)
corrected_df3 = corrected_df3.sort_index()
c = corrected_df3[corrected_df3[['respiratory rate', 'temperature of extremities']].isna().any(1)]

df6 = pd.concat([c[c['outcome']==2], c[c['outcome']==3]], axis =0)

df6['respiratory rate'] = df6['respiratory rate'].fillna(death_all['respiratory rate'].median())
df6['temperature of extremities'] = df6['temperature of extremities'].fillna(death_all['temperature of extremities'].median()) 

df7 = c[c['outcome']==1]

df7['respiratory rate'] = df7['respiratory rate'].fillna(alive['respiratory rate'].median())
df7['temperature of extremities'] = df7['temperature of extremities'].fillna(alive['temperature of extremities'].median())

df8 = pd.concat([df6, df7], axis =0)


corrected_list4 = df8.index.tolist()
not_corrected_df4 = corrected_df3.copy()
for i in corrected_list4:
  not_corrected_df4 = not_corrected_df4.drop(index = i)

corrected_df4 = pd.concat([df8, not_corrected_df4], axis = 0)
corrected_df4 = corrected_df4.sort_index()
corrected_df4

#8

corrected_df4.describe()

#9
new_df.describe()

"""1. НАЗВАНИЕ: База данных Horse Colic

2. Исходная информация
   -- Создатели: Мэри Маклиш и Мэтт Сесиль
Департамент компьютерных наук
Университет Гвельфа
Гвельф, Онтарио, Канада N1G 2W1
mdmcleish@water.waterloo.edu
   -- Донор: Уилл Тейлор (taylor@pluto.arc.nasa.gov)
   -- Дата: 06.08.89

3. Использование в прошлом:
   -- Неизвестный

4. Соответствующая информация:

   -- 2 файла данных
      -- horse-colic.data: 300 тренировочных экземпляров
      -- horse-colic.test: 68 тестовых экземпляров
   -- Возможные атрибуты класса: 24 (независимо от того, является ли поражение хирургическим)
     -- другие включают: 23, 25, 26 и 27
   -- Многие типы данных: (непрерывные, дискретные и номинальные)

5. Количество экземпляров: 368 (300 для обучения, 68 для тестирования)

6. Количество атрибутов: 28

7. Информация об атрибутах:

  1: операция?
          1 = да, была операция
          2 = лечили без операции

  2: Возраст
          1 = взрослая лошадь
          2 = Молодой (< 6 месяцев)

  3: Номер больницы
          - числовой идентификатор
          - номер случая, присвоенный лошади (может быть не уникальным, если лошадь лечится > 1 раза)

  4: ректальная температура
          - линейный
          - в градусах Цельсия.
          - Повышенная температура может возникнуть из-за инфекции.
          - температура может быть снижена, когда животное находится в позднем шоке
          - нормальная температура 37,8
          - этот параметр обычно меняется по мере развития проблемы
например. может начаться нормально, затем стать повышенным из-за поражения, возвращаясь к нормальному диапазону, когда лошадь впадает в шок
  
  5: пульс
          - линейный
          - частота сердечных сокращений в ударах в минуту
          - является отражением состояния сердца: 30-40 нормально для взрослых
          - редко бывает ниже нормы, хотя спортивные лошади могут иметь норму 20-25
          - у животных с болезненными поражениями или страдающих от циркуляторного шока может быть учащенное сердцебиение

  6: частота дыхания
          - линейный
          - нормальная скорость от 8 до 10
          - полезность сомнительна из-за больших колебаний

  7: температура конечностей
          - субъективное указание на периферическое кровообращение
          - возможные значения:
               1 = нормальный
               2 = теплый
               3 = прохладный
               4 = холодный
          - холодные или холодные конечности указывают на возможный шок
          - горячие конечности должны коррелировать с повышенной ректальной температурой.

  8: периферический пульс
          - субъективный
          - возможные значения:
               1 = нормальный
               2 = увеличено
               3 = уменьшено
               4 = отсутствует
          - нормальный или повышенный п.п. указывают на адекватное кровообращение, в то время как снижение или отсутствие указывают на плохую перфузию

  9: слизистые оболочки
          - субъективное измерение цвета
          - возможные значения:
               1 = обычный розовый
               2 = ярко-розовый
               3 = бледно-розовый
               4 = бледно-цианотичный
               5 = ярко-красный / введенный
               6 = темный цианотичный
          - 1 и 2, вероятно, указывают на нормальное или слегка повышенное кровообращение
          - 3 могут возникать при раннем шоке
          - 4 и 6 указывают на серьезное нарушение кровообращения
          - 5 больше указывает на септицемию

 10: время наполнения капилляров
          - клиническое заключение. Чем дольше заправка, тем хуже циркуляция
          - возможные значения
               1 = < 3 секунд
               2 = >= 3 секунды

 11: боль - субъективная оценка уровня боли лошади.
          - возможные значения:
               1 = тревога, боли нет
               2 = депрессия
               3 = перемежающаяся легкая боль
               4 = перемежающаяся сильная боль
               5 = постоянная сильная боль
          - НЕ следует рассматривать как упорядоченную или дискретную переменную!
          - В целом, чем больнее, тем больше вероятность, что потребуется хирургическое вмешательство.
          - предшествующее лечение боли может в некоторой степени маскировать уровень боли

 12: перистальтика
          - показатель активности в кишечнике лошади. как кишка
            становится более растянутой или лошадь становится более токсичной, снижается активность
          - возможные значения:
               1 = гипермобильный
               2 = нормальный
               3 = гипомобильный
               4 = отсутствует

 13: вздутие живота
          - ВАЖНЫЙ параметр.
          - возможные значения
               1 = нет
               2 = легкий
               3 = умеренный
               4 = тяжелый
          - животное с вздутием живота, вероятно, будет болезненным и у него снижена перистальтика кишечника.
          - лошади с сильным вздутием живота, скорее всего, потребуется хирургическое вмешательство только для того, чтобы уменьшить давление.

 14: назогастральный зонд
          - это относится к любому газу, выходящему из трубки
          - возможные значения:
               1 = нет
               2 = легкий
               3 = значительный
          - большая газовая шапка в желудке может доставить дискомфорт лошади

 15: назогастральный рефлюкс
          - возможные значения
               1 = нет
               2 = > 1 литр
               3 = < 1 литра
          - чем больше количество рефлюкса, тем больше вероятность того, что существует серьезное препятствие для прохождения жидкости из остальной части кишечника

 16: назогастральный рефлюкс ЛГ
          - линейный
          - шкала от 0 до 14, где 7 - нейтрально
          - нормальные значения находятся в диапазоне от 3 до 4

 17: ректальное исследование - кал
          - возможные значения
               1 = нормальный
               2 = увеличено
               3 = уменьшилось
               4 = отсутствует
          - отсутствие кала, вероятно, указывает на непроходимость

 18: живот
          - возможные значения
               1 = нормальный
               2 = другое
               3 = твердый кал в толстой кишке
               4 = растянутая тонкая кишка
               5 = растянутая толстая кишка
          - 3, вероятно, обструкция, вызванная механическим столкновением и обычно лечится медикаментозно.
          - 4 и 5 указывают на хирургическое поражение

 19: объем упакованных клеток
          - линейный
          - количество эритроцитов по объему в крови
          - нормальный диапазон составляет от 30 до 50. Уровень повышается при нарушении кровообращения или при обезвоживании животного.

 20: общий белок
          - линейный
          - нормальные значения лежат в диапазоне 6-7,5 (г/дл)
          - чем выше значение, тем больше обезвоживание

 21: внешний вид абдоминоцентеза
          - в живот лошади вводят иглу и получают жидкость из брюшной полости
          - возможные значения:
               1 = очистить
               2 = облачно
               3 = серозно-геморрагический
          - нормальная жидкость прозрачная, а мутная или серозно-геморрагическая свидетельствует о поражении кишечника

 22: общий белок абдомоцентеза
          - линейный
          - чем выше уровень белка, тем выше вероятность нарушения работы кишечника. Значения указаны в г/дл

 23: исход
          - что в итоге случилось с лошадью?
          - возможные значения:
               1 = жил
               2 = умер
               3 = был усыплен

 24: хирургическое поражение?
          - ретроспективно, была ли проблема (поражение) хирургической?
          - все случаи либо оперированы, либо вскрыты, так что это значение и тип поражения всегда известны
          - возможные значения:
               1 = Да
               2 = нет

 25, 26, 27: тип поражения
          - первая цифра - место поражения
               1 = желудочный
               2 = тонкий кишечник
               3 = длинная кишка
               4 = lg толстой и слепой кишки
               5 = слепая кишка
               6 = поперечно-ободочная кишка
               7 = задняя/нисходящая кишка
               8 = матка
               9 = мочевой пузырь
               11 = все участки кишечника
               00 = нет
          - вторая цифра тип
               1 = простой
               2 = удушение
               3 = воспаление
               4 = другое
          - третья цифра - подтип
               1 = механический
               2 = паралитический
               0 = н/д
          - четвертая цифра - специальный код
               1 = обтурация
               2 = внутренний
               3 = внешний
               4 = адинамический
               5 = заворот/кручение
               6 = инвагинация
               7 = тромбоэмболия
               8 = грыжа
               9 = липома/сленическое ущемление
               10 = смещение
               0 = н/д
 28: cp_data
          - имеются ли данные патологии для этого случая?
               1 = Да
               2 = нет
          - эта переменная не имеет значения, поскольку данные патологии не включаются и не собираются для этих случаев.

8. Отсутствующие значения: 30% значений отсутствуют.

1. TItle: Horse Colic database

2. Source Information
   -- Creators: Mary McLeish & Matt Cecile
	  	Department of Computer Science
		University of Guelph
		Guelph, Ontario, Canada N1G 2W1
		mdmcleish@water.waterloo.edu
   -- Donor:    Will Taylor (taylor@pluto.arc.nasa.gov)
   -- Date:     8/6/89

3. Past Usage:
   -- Unknown

4. Relevant Information:

   -- 2 data files
      -- horse-colic.data: 300 training instances
      -- horse-colic.test: 68 test instances
   -- Possible class attributes: 24 (whether lesion is surgical)
     -- others include: 23, 25, 26, and 27
   -- Many Data types: (continuous, discrete, and nominal)

5. Number of Instances: 368 (300 for training, 68 for testing)

6. Number of attributes: 28

7. Attribute Information:

  1:  surgery?
          1 = Yes, it had surgery
          2 = It was treated without surgery

  2:  Age
          1 = Adult horse
          2 = Young (< 6 months)

  3:  Hospital Number
          - numeric id
          - the case number assigned to the horse (may not be unique if the horse is treated > 1 time)

  4:  rectal temperature
          - linear
          - in degrees celsius.
          - An elevated temp may occur due to infection.
          - temperature may be reduced when the animal is in late shock
          - normal temp is 37.8
          - this parameter will usually change as the problem progresses
eg. may start out normal, then become elevated because of the lesion, passing back through the normal range as the horse goes into shock
  5:  pulse
          - linear
          - the heart rate in beats per minute
          - is a reflection of the heart condition: 30 -40 is normal for adults
          - rare to have a lower than normal rate although athletic horses may have a rate of 20-25
          - animals with painful lesions or suffering from circulatory shock may have an elevated heart rate

  6:  respiratory rate
          - linear
          - normal rate is 8 to 10
          - usefulness is doubtful due to the great fluctuations

  7:  temperature of extremities
          - a subjective indication of peripheral circulation
          - possible values:
               1 = Normal
               2 = Warm
               3 = Cool
               4 = Cold
          - cool to cold extremities indicate possible shock
          - hot extremities should correlate with an elevated rectal temp.

  8:  peripheral pulse
          - subjective
          - possible values are:
               1 = normal
               2 = increased
               3 = reduced
               4 = absent
          - normal or increased p.p. are indicative of adequate circulation while reduced or absent indicate poor perfusion

  9:  mucous membranes
          - a subjective measurement of colour
          - possible values are:
               1 = normal pink
               2 = bright pink
               3 = pale pink
               4 = pale cyanotic
               5 = bright red / injected
               6 = dark cyanotic
          - 1 and 2 probably indicate a normal or slightly increased circulation
          - 3 may occur in early shock
          - 4 and 6 are indicative of serious circulatory compromise
          - 5 is more indicative of a septicemia

 10: capillary refill time
          - a clinical judgement. The longer the refill, the poorer the circulation
          - possible values
               1 = < 3 seconds
               2 = >= 3 seconds

 11: pain - a subjective judgement of the horse's pain level
          - possible values:
               1 = alert, no pain
               2 = depressed
               3 = intermittent mild pain
               4 = intermittent severe pain
               5 = continuous severe pain
          - should NOT be treated as a ordered or discrete variable!
          - In general, the more painful, the more likely it is to require surgery
          - prior treatment of pain may mask the pain level to some extent

 12: peristalsis
          - an indication of the activity in the horse's gut. As the gut
            becomes more distended or the horse becomes more toxic, the activity decreases
          - possible values:
               1 = hypermotile
               2 = normal
               3 = hypomotile
               4 = absent

 13: abdominal distension
          - An IMPORTANT parameter.
          - possible values
               1 = none
               2 = slight
               3 = moderate
               4 = severe
          - an animal with abdominal distension is likely to be painful and have reduced gut motility.
          - a horse with severe abdominal distension is likely to require surgery just tio relieve the pressure

 14: nasogastric tube
          - this refers to any gas coming out of the tube
          - possible values:
               1 = none
       2 = slight
               3 = significant
          - a large gas cap in the stomach is likely to give the horse discomfort

 15: nasogastric reflux
          - possible values
               1 = none
               2 = > 1 liter
               3 = < 1 liter
          - the greater amount of reflux, the more likelihood that there is some serious obstruction to the fluid passage from the rest of the intestine

 16: nasogastric reflux PH
          - linear
          - scale is from 0 to 14 with 7 being neutral
          - normal values are in the 3 to 4 range

 17: rectal examination - feces
          - possible values
               1 = normal
               2 = increased
               3 = decreased
               4 = absent
          - absent feces probably indicates an obstruction

 18: abdomen
          - possible values
               1 = normal
               2 = other
               3 = firm feces in the large intestine
               4 = distended small intestine
               5 = distended large intestine
          - 3 is probably an obstruction caused by a mechanical impaction and is normally treated medically
          - 4 and 5 indicate a surgical lesion

 19: packed cell volume
          - linear
          - the # of red cells by volume in the blood
          - normal range is 30 to 50. The level rises as the circulation becomes compromised or as the animal becomes dehydrated.

 20: total protein
          - linear
          - normal values lie in the 6-7.5 (gms/dL) range
          - the higher the value the greater the dehydration

 21: abdominocentesis appearance
          - a needle is put in the horse's abdomen and fluid is obtained from the abdominal cavity
          - possible values:
               1 = clear
               2 = cloudy
               3 = serosanguinous
          - normal fluid is clear while cloudy or serosanguinous indicates a compromised gut

 22: abdomcentesis total protein
          - linear
          - the higher the level of protein the more likely it is to have a compromised gut. Values are in gms/dL

 23: outcome
          - what eventually happened to the horse?
          - possible values:
               1 = lived
               2 = died
               3 = was euthanized

 24: surgical lesion?
          - retrospectively, was the problem (lesion) surgical?
          - all cases are either operated upon or autopsied so that this value and the lesion type are always known
          - possible values:
               1 = Yes
               2 = No

 25, 26, 27: type of lesion
          - first number is site of lesion
               1 = gastric
               2 = sm intestine
               3 = lg colon
               4 = lg colon and cecum
               5 = cecum
               6 = transverse colon
               7 = retum/descending colon
               8 = uterus
               9 = bladder
               11 = all intestinal sites
               00 = none
          - second number is type
               1 = simple
               2 = strangulation
               3 = inflammation
               4 = other
          - third number is subtype
               1 = mechanical
               2 = paralytic
               0 = n/a
          - fourth number is specific code
               1 = obturation
               2 = intrinsic
               3 = extrinsic
               4 = adynamic
               5 = volvulus/torsion
               6 = intussuption
               7 = thromboembolic
               8 = hernia
               9 = lipoma/slenic incarceration
               10 = displacement
               0 = n/a
 28: cp_data
          - is pathology data present for this case?
               1 = Yes
               2 = No
          - this variable is of no significance since pathology data is not included or collected for these cases

8. Missing values: 30% of the values are missing
"""

